### ISSUE TITLE
Using kibosh in production systems?

### ISSUE THREAD

**Issue by aegershman** [cf-platform-eng/kibosh#36]
As a PCF operator I've had a growing number of teams come to me who are interested in getting PKS clusters just so they can run data services on kubernetes (neo4j, solr) and consume it in PAS. Most of these teams don't want (or should have) the responsibility of maintaining their own kubernetes cluster. My team has lead time to make a decision, but we're going to have to decide how we want to handle this.

I think kibosh could be a great solution for us. With that said:

- What are the long-term goals of this project? Is it at risk of going away anytime soon?
- Will this ever become an "official" Pivotal product where the bazaar tile is released on pivnet?
- Should I be concerned about the frequency of [releases and little release notes?](https://github.com/cf-platform-eng/kibosh/releases) (Sorry I genuinely don't mean that as a dig or anything)
- In your own opinion, how closely do you respect semantic versioning? E.g., should I be worried about minor or patch versions breaking things?
- *In general, in your own opinion, with this being a totally non-binding, no-expectations question*, with the current state of kibosh, do you think it _could_ be a good idea to use kibosh in production with a small number of data services?

I appreciate any feedback 👍

**Comment by cholick** [comment]
With respect to frequency of releases & semantic versioning:
We currently have a pipelines that are taking every commit and bundling things into a Github release with a new `patch` version number, assuming they pass CI installing the BOSH release and building the integration tests.

We're bumping the `minor` component when we do a breaking change. It's early yet. We didn't want to release a `1.0`, since that carries a bit of semantic meaning. So we're kind of treading `patch` like `minor` and `minor` like `major`.

**Comment by aegershman** [comment]
Thanks for getting back to me on this, I appreciate it 👌
